[package]
name = "cloakpay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.2"
# Added this for test runners and cheatcodes (like start_cheat_caller)
snforge_std = "0.27.0" 

[[target.starknet-contract]]
sierra = true
# Enable CASM for local testing and deployment
casm = true 

[[test]]
name = "cloakpay_tests"

[dev-dependencies]
# Ensures snforge is available specifically for the test target
snforge_std = "0.27.0"